// <auto-generated />
using Core.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(BitirmeContext))]
    [Migration("20190530085029_AddTableBegeniler")]
    partial class AddTableBegeniler
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Tables.Begeniler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KullaniciAdi");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.ToTable("Begeniler");
                });

            modelBuilder.Entity("Core.Tables.Konular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hakkinda");

                    b.Property<string>("KonuAdi");

                    b.Property<string>("Resim");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("Core.Tables.KonuYazarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KonularIdi");

                    b.Property<int>("KullanicilarIdi");

                    b.HasKey("Id");

                    b.HasIndex("KonularIdi");

                    b.HasIndex("KullanicilarIdi");

                    b.ToTable("KonuYazarlar");
                });

            modelBuilder.Entity("Core.Tables.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<float>("Bakiye");

                    b.Property<string>("Biyografi");

                    b.Property<string>("Email");

                    b.Property<string>("KullaniciAdi");

                    b.Property<string>("Resim");

                    b.Property<string>("Sifre");

                    b.Property<string>("Soyad");

                    b.Property<string>("Telefon");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Core.Tables.Makaleler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltBaslik");

                    b.Property<string>("Baslik");

                    b.Property<string>("Icerik");

                    b.Property<int>("KonuIdi");

                    b.Property<int>("KullaniciIdi");

                    b.Property<bool>("Paylasilma");

                    b.Property<string>("Resim");

                    b.Property<string>("Slug");

                    b.Property<string>("Tarih");

                    b.Property<int>("VerilenPara");

                    b.HasKey("Id");

                    b.HasIndex("KonuIdi");

                    b.HasIndex("KullaniciIdi");

                    b.ToTable("Makaleler");
                });

            modelBuilder.Entity("Core.Tables.Personeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Email");

                    b.Property<string>("KullaniciAdi");

                    b.Property<string>("Sifre");

                    b.Property<string>("Soyad");

                    b.Property<string>("Tc");

                    b.Property<string>("Telefon");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("Core.Tables.Reklamlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad");

                    b.Property<string>("Baslik");

                    b.Property<string>("Resim");

                    b.Property<string>("Tarih");

                    b.Property<int>("Tur");

                    b.Property<int>("YayinKalkisTarih");

                    b.Property<bool>("YayinOnay");

                    b.HasKey("Id");

                    b.ToTable("Reklamlar");
                });

            modelBuilder.Entity("Core.Tables.Yorumlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad");

                    b.Property<string>("Email");

                    b.Property<int>("MakalelerIdi");

                    b.Property<bool>("Onaylanma");

                    b.Property<string>("YapilanTarih");

                    b.Property<string>("YapilanYorum");

                    b.HasKey("Id");

                    b.HasIndex("MakalelerIdi");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("Core.Tables.KonuYazarlar", b =>
                {
                    b.HasOne("Core.Tables.Konular", "KonularId")
                        .WithMany()
                        .HasForeignKey("KonularIdi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Tables.Kullanicilar", "KullanicilarId")
                        .WithMany()
                        .HasForeignKey("KullanicilarIdi")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Tables.Makaleler", b =>
                {
                    b.HasOne("Core.Tables.Konular", "KonuId")
                        .WithMany()
                        .HasForeignKey("KonuIdi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Tables.Kullanicilar", "KullaniciId")
                        .WithMany()
                        .HasForeignKey("KullaniciIdi")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Tables.Yorumlar", b =>
                {
                    b.HasOne("Core.Tables.Makaleler", "MakalelerId")
                        .WithMany()
                        .HasForeignKey("MakalelerIdi")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
